version: '3.5'

services:
#  nginx:
#    image: nginx:1.17-alpine
#    container_name: nginx
#    ports:
#      - 80:80
#    volumes:
#      - ./nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf
#    depends_on:
#      - cvbackend
#    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

  nginx:
    image: nginx:1.17-alpine
    container_name: nginx
    depends_on:
      - cvbackend
    ports:
      - 80:80
    volumes:
      - ./src:/src
      - ./nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"


  cvbackend:
    build:
      context: ./src
      dockerfile: Dockerfile
    container_name: cvbackend
    expose:
      - "8000"
    volumes:
      - static_volume:/home/cvbackend/web/static
      - media_volume:/home/cvbackend/web/media
    image: cvbackendimage
    restart: on-failure

volumes:
  static_volume:
  media_volume:
